name: 'Lint PR'

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #   wip: true  https://github.com/amannn/action-semantic-pull-request/issues/249
          requireScope: false
          types: |
            revert
            fix
            feat
            increment
            ops
            qa
            refactor
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
